version: '3.1'
services:
  sidekick-test-mode:
    image: runsidekick/sidekick-test-mode:latest
    restart: always
    container_name: sidekick-test-mode
    ports:
      - "80:80"
    env_file: .env