# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build (Java)

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v14
        with:
          repositories:
            '[
              { "id": "thundra-infra-releases", "url": "https://repo.thundra.io/content/repositories/thundra-infra-releases"},
              { "id": "thundra-infra-snapshots", "url": "https://repo.thundra.io/content/repositories/thundra-infra-snapshots"},
              { "id": "sidekick-infra-releases", "url": "https://repo.thundra.io/content/repositories/sidekick-infra-releases"},
              { "id": "sidekick-infra-snapshots", "url": "https://repo.thundra.io/content/repositories/sidekick-infra-snapshots"},
              { "id": "sidekick-oss-releases", "url": "https://repo.thundra.io/content/repositories/sidekick-oss-releases"},
              { "id": "sidekick-oss-snapshots", "url": "https://repo.thundra.io/content/repositories/sidekick-oss-snapshots"}
            ]'
          servers:
            '[
              { "id": "thundra-infra-releases", "username": "${{ secrets.THUNDRA_INTERNAL_REPO_USERNAME}}", "password": "${{ secrets.THUNDRA_INTERNAL_REPO_PASSWORD}}"},
              { "id": "thundra-infra-snapshots", "username": "${{ secrets.THUNDRA_INTERNAL_REPO_USERNAME}}", "password": "${{ secrets.THUNDRA_INTERNAL_REPO_PASSWORD}}"},
              { "id": "sidekick-infra-releases", "username": "${{ secrets.SIDEKICK_INTERNAL_REPO_USERNAME}}", "password": "${{ secrets.SIDEKICK_INTERNAL_REPO_PASSWORD}}"},
              { "id": "sidekick-infra-snapshots", "username": "${{ secrets.SIDEKICK_INTERNAL_REPO_USERNAME}}", "password": "${{ secrets.SIDEKICK_INTERNAL_REPO_PASSWORD}}"},
              { "id": "sidekick-oss-releases", "username": "${{ secrets.SIDEKICK_INTERNAL_REPO_USERNAME}}", "password": "${{ secrets.SIDEKICK_INTERNAL_REPO_PASSWORD}}"},
              { "id": "sidekick-oss-snapshots", "username": "${{ secrets.SIDEKICK_INTERNAL_REPO_USERNAME}}", "password": "${{ secrets.SIDEKICK_INTERNAL_REPO_PASSWORD}}"}
            ]'
      - name: Build with Maven
        run: mvn -q clean install
